### PR TITLE
Include license file in published crates

### PR DESCRIPTION
**Pull request by ankane**
Hi, thanks for this project! This symlinks the license file so it's included in the published crates.

### CODE REVIEW

**Comment by Nugine** [comment]
Thanks! Is there any background for this PR? 
The license in `Cargo.toml` is `license = "MIT"`. Previously I thought it was enough for license checkers.

**Review by Nugine — APPROVED** [review]

**Comment by ankane** [comment]
Hi @Nugine, the MIT license mentions including it with copies of the software, and it's nice for things like `cargo vendor` (https://github.com/microsoft/windows-rs/issues/1587#issuecomment-1063010186).

**Comment by Nugine** [comment]
`v0.9` is now waiting for #46 .
Do you need a patch version `v0.8.1` with this PR backported?

**Comment by ankane** [comment]
Thanks @Nugine! No need to backport (I can include it manually) - just thought it'd be good for future releases.

**Pull request merged**
